name: Build and Push Docker Image
 
on:
    push:
        branches:
            - main
 
 
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout code
            uses: actions/checkout@v3
          - name: Set up Docker Buildx
            uses: docker/setup-buildx-action@v2
 
          - name: log in to Docker Hub
            uses: docker/login-action@v2
            with:
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_PASSWORD }}
 
          - name: Build Docker image  # Construye la imagen con el mensaje del commit como tag
            run: |
              commit_message="${{ github.event.head_commit.message }}"
              # Reemplaza espacios con guiones y recorta el mensaje si es muy largo
              tag=$(echo "$commit_message" | tr '[:space:]' '-' | cut -c 1-50)
              echo "Building Docker image with tag: $tag"
              docker build -t daniielpro10/hola-mundo-node:$tag .
 
          - name: Push Docker image  # Empuja la imagen construida al Docker Hub
            run: |
              docker push daniielpro10/hola-mundo-node:$tag